#必须保存为UTF-8 否则git会报异常
spring:
    profiles:
        active:
        - dev


---
spring:
    profiles: dev
    application:
        name: cloud-config-dev
        
---
spring:
    profiles: dev
    application:
        name: cloud-config-test  